accessLogsBufferSize: 50
cluster: $REMOTE_CLUSTER
devMode: false
ext-auth-service:
  enabled: false
  extraTemplateAnnotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
insecure: false
istiodSidecar:
  createRoleBinding: false
  istiodServiceAccount:
    name: istiod
    namespace: istio-system
leaderElection: true
maxGrpcMessageSize: "4294967295"
metricsBufferSize: 50
rate-limiter:
  enabled: false
  extraTemplateAnnotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
relay:
  authority: gloo-mesh-mgmt-server.gloo-mesh
  clientTlsSecret:
    name: relay-client-tls-secret
  rootTlsSecret:
    name: relay-root-tls-secret
  serverAddress: $MGMT_SERVER_NETWORKING_ADDRESS
  tokenSecret:
    key: token
    name: relay-identity-token-secret
    namespace: ""
verbose: false


glooMeshAgent:
  enabled: true
  env:
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  floatingUserId: false
  image:
    pullPolicy: IfNotPresent
    registry: gcr.io/gloo-mesh
    repository: gloo-mesh-agent
    tag: $GLOO_MESH_VERSION
  ports:
    grpc: 9977
    stats: 9091
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  runAsUser: 10101
  serviceType: ClusterIP
  sidecars: {}