# Be sure to change all instances of $CLUSTER_NAME to the name of the workload cluster.
# This value must match the value that you plan to use when you register the cluster with the Gloo Mesh management plane.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-eastwestgateway
  # Deploy to the east-west gateway namespace. If using one namespace for gateways, specify 'istio-gateways' instead.
  namespace: istio-eastwest
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest-gateway-$REVISION
  # Deploy to the east-west gateway namespace. If using one namespace for gateways, specify 'istio-gateways' instead.
  namespace: istio-eastwest
spec:
  # No control plane components are installed
  profile: empty
  # Solo.io Istio distribution repository; required for Gloo Mesh Istio.
  hub: gcr.io/istio-enterprise
  # The Solo.io Gloo Mesh Istio tag
  tag: $VERSION_TAG
  # Istio revision to create resources with
  revision: $REVISION
  
  components:
    ingressGateways:
    # Enable the default east-west gateway
      - name: istio-eastwestgateway-$REVISION
        # Deploy to the east-west gateway namespace. If using one namespace for gateways, specify 'istio-gateways' instead.
        namespace: istio-eastwest
        enabled: true
        label:
          istio: eastwestgateway
          version: $REVISION
          app: istio-eastwestgateway
          # Matches spec.values.global.network in the istiod deployment
          topology.istio.io/network: $CLUSTER_NAME
        k8s:
          hpaSpec:
            maxReplicas: 5
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 60
                type: Resource
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-eastwestgateway-$REVISION
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 25%
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 40Mi
          env:
            # Required by Gloo Mesh for east/west routing
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          service:
            # Create a ClusterIP service for this gateway, because a LoadBalancer service is created separately
            type: ClusterIP
            # Match the LoadBalancer service
            ports:
            # Health check port. For AWS ELBs, this port must be listed first.
            - name: status-port
              port: 15021
              targetPort: 15021
            # Port for multicluster mTLS passthrough; required for Gloo Mesh east/west routing
            - port: 15443
              targetPort: 15443
              # Gloo Mesh looks for this default name 'tls' on an ingress gateway
              name: tls
        overlays:
          # Update role binding to use shared service account
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            name: istio-eastwestgateway-$REVISION-sds
            patches:
              - path: subjects.[0]
                value:
                  name: "istio-eastwestgateway"
                  kind: ServiceAccount
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-eastwestgateway-$REVISION
            patches:
              # Update the deployment to use shared service account
              - path: spec.template.spec.serviceAccountName
                value: "istio-eastwestgateway"
              - path: spec.template.spec.serviceAccount
                value: "istio-eastwestgateway"
              # Sleep 25s on pod shutdown to allow connections to drain
              - path: spec.template.spec.containers.[name:istio-proxy].lifecycle
                value:
                  preStop:
                    exec:
                      command:
                      - sleep
                      - "25"
              # Schedule pods on separate nodes if possible
              - path: spec.template.spec.affinity
                value:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - podAffinityTerm:
                        labelSelector:
                          matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - istio-eastwestgateway-$REVISION
                        topologyKey: kubernetes.io/hostname
                      weight: 100

  # Helm values overrides
  values:
    # https://istio.io/v1.5/docs/reference/config/installation-options/#global-options
    global:
      # Required for connecting VirtualMachines to the mesh
      network: $CLUSTER_NAME
      # Required for annotating Istio metrics with the cluster name.
      # Must match the trustDomain and GLOO_MESH_CLUSTER_NAME
      multiCluster:
        clusterName: $CLUSTER_NAME