apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  # Deploy to the ingress gateway namespace. If using one namespace for gateways, specify 'istio-gateways' instead.
  namespace: istio-ingress
spec:
  type: LoadBalancer
  selector:
    istio: ingressgateway
    version: $REVISION
  ports:
  # Health check port. For AWS ELBs, this port must be listed first.
  - name: status-port
    port: 15021
    targetPort: 15021
  # Main HTTP ingress port
  - port: 80
    targetPort: 8080
    name: http2
  # Main HTTPS ingress port
  - port: 443
    targetPort: 8443
    name: https