apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  # No control plane components are installed
  profile: empty
  # Solo.io Istio distribution repository; required for Gloo Mesh Istio. You get the repo key from your Solo Account Representative.
  hub: $REPO
  # The Solo.io Gloo Mesh Istio tag
  tag: $ISTIO_VERSION
  # Istio revision to create resources with
  revision: $REVISION
  
  components:
    ingressGateways:
    # Enable the default ingress gateway
      - name: istio-ingressgateway
        # Deploy to the ingress gateway namespace. If using one namespace for gateways, specify 'istio-gateways' instead.
        namespace: istio-ingress
        enabled: true
        label:
          # Set a unique label for the gateway. This is required to ensure Gateways
          # can select this workload
          istio: ingressgateway
          version: $REVISION
          app: istio-ingressgateway
          # Matches spec.values.global.network in the istiod deployment
          topology.istio.io/network: $CLUSTER_NAME

  # Helm values overrides
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
    # https://istio.io/v1.5/docs/reference/config/installation-options/#global-options
    global:
      # Required for connecting VirtualMachines to the mesh
      network: $CLUSTER_NAME
      # Required for annotating Istio metrics with the cluster name.
      # Must match the trustDomain and GLOO_MESH_CLUSTER_NAME
      multiCluster:
        clusterName: $CLUSTER_NAME