apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-frontend
  namespace: backstage
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-frontend
  namespace: backstage
  labels:
    app: backstage-frontend
    service: backstage-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: backstage-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-frontend
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-frontend
  template:
    metadata:
      labels:
        app: backstage-frontend
    spec:
      serviceAccountName: backstage-frontend
      containers:
        - image: gcr.io/solo-public/docs/portal-backstage-frontend:latest
          #args: ["--host", "0.0.0.0"]
          envFrom:
          - secretRef:
            name: postgres-secrets
          - secretRef:
            name: backstage-secrets
          imagePullPolicy: Always
          name: backstage-frontend
          ports:
          - name: http
            containerPort: 7007