apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiDoc
metadata:
  name: ratings-graphql-apidoc
  namespace: bookinfo
spec:
  graphql:
    schemaDefinition: |-
      type Query {
          GetRatings(id: String): Ratings 
        }
        type Ratings {
          ratings: [Rating]
        }
        """A book rating"""
        type Rating {
          """Name of the user peforming the rating"""
          reviewer: String
          """Number of stars for this rating"""
          numStars: Int
        }